version=0.1

# ==================== awsaccountname====================

[awsaccountname-us-east-1]
[awsaccountname-us-east-1.deploy.parameters]
stack_name = "sam-prod-cloudwatch-loggroup-retention"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
s3_bucket = "bucketname"
s3_prefix = "sam/prod-cloudwatch-loggroup-retention"
confirm_changeset = true
disable_rollback = false
